/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamIndexRouteImport } from './routes/stream/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as SearchChar91termChar93IndexRouteImport } from './routes/search/[term]/index'
import { Route as TvIdInfoIndexRouteImport } from './routes/tv/$id/info/index'
import { Route as TvIdWatchEpisodeNumberIndexRouteImport } from './routes/tv/$id/watch/$episode/$number/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamIndexRoute = StreamIndexRouteImport.update({
  id: '/stream/',
  path: '/stream/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const SearchChar91termChar93IndexRoute =
  SearchChar91termChar93IndexRouteImport.update({
    id: '/search/term/',
    path: '/search/term/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TvIdInfoIndexRoute = TvIdInfoIndexRouteImport.update({
  id: '/tv/$id/info/',
  path: '/tv/$id/info/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIdWatchEpisodeNumberIndexRoute =
  TvIdWatchEpisodeNumberIndexRouteImport.update({
    id: '/tv/$id/watch/$episode/$number/',
    path: '/tv/$id/watch/$episode/$number/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/profile/': typeof ProfileIndexRoute
  '/stream/': typeof StreamIndexRoute
  '/search/term/': typeof SearchChar91termChar93IndexRoute
  '/tv/$id/info/': typeof TvIdInfoIndexRoute
  '/tv/$id/watch/$episode/$number/': typeof TvIdWatchEpisodeNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/profile': typeof ProfileIndexRoute
  '/stream': typeof StreamIndexRoute
  '/search/term': typeof SearchChar91termChar93IndexRoute
  '/tv/$id/info': typeof TvIdInfoIndexRoute
  '/tv/$id/watch/$episode/$number': typeof TvIdWatchEpisodeNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/test': typeof TestRoute
  '/profile/': typeof ProfileIndexRoute
  '/stream/': typeof StreamIndexRoute
  '/search/term/': typeof SearchChar91termChar93IndexRoute
  '/tv/$id/info/': typeof TvIdInfoIndexRoute
  '/tv/$id/watch/$episode/$number/': typeof TvIdWatchEpisodeNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/about'
    | '/test'
    | '/profile/'
    | '/stream/'
    | '/search/term/'
    | '/tv/$id/info/'
    | '/tv/$id/watch/$episode/$number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/test'
    | '/profile'
    | '/stream'
    | '/search/term'
    | '/tv/$id/info'
    | '/tv/$id/watch/$episode/$number'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/about'
    | '/test'
    | '/profile/'
    | '/stream/'
    | '/search/term/'
    | '/tv/$id/info/'
    | '/tv/$id/watch/$episode/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  TestRoute: typeof TestRoute
  StreamIndexRoute: typeof StreamIndexRoute
  SearchChar91termChar93IndexRoute: typeof SearchChar91termChar93IndexRoute
  TvIdInfoIndexRoute: typeof TvIdInfoIndexRoute
  TvIdWatchEpisodeNumberIndexRoute: typeof TvIdWatchEpisodeNumberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/': {
      id: '/stream/'
      path: '/stream'
      fullPath: '/stream/'
      preLoaderRoute: typeof StreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/search/term/': {
      id: '/search/term/'
      path: '/search/term'
      fullPath: '/search/term/'
      preLoaderRoute: typeof SearchChar91termChar93IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id/info/': {
      id: '/tv/$id/info/'
      path: '/tv/$id/info'
      fullPath: '/tv/$id/info/'
      preLoaderRoute: typeof TvIdInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$id/watch/$episode/$number/': {
      id: '/tv/$id/watch/$episode/$number/'
      path: '/tv/$id/watch/$episode/$number'
      fullPath: '/tv/$id/watch/$episode/$number/'
      preLoaderRoute: typeof TvIdWatchEpisodeNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  TestRoute: TestRoute,
  StreamIndexRoute: StreamIndexRoute,
  SearchChar91termChar93IndexRoute: SearchChar91termChar93IndexRoute,
  TvIdInfoIndexRoute: TvIdInfoIndexRoute,
  TvIdWatchEpisodeNumberIndexRoute: TvIdWatchEpisodeNumberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
